"""add_telegram_id_to_receipts

Revision ID: 388ad5953b46
Revises: 8d3410378c94
Create Date: 2026-04-21 20:15:24.366853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '388ad5953b46'
down_revision: Union[str, None] = '8d3410378c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_id', sa.BigInteger(), nullable=True))
        batch_op.create_index(batch_op.f('ix_receipts_telegram_id'), ['telegram_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipts_telegram_id'))
        batch_op.drop_column('telegram_id')

    # ### end Alembic commands ###