"""add unique constraint to receipts

Revision ID: a86e588842e9
Revises: b7e2f4a1c903
Create Date: 2026-05-04 22:19:48.707413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a86e588842e9'
down_revision: Union[str, None] = 'b7e2f4a1c903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_receipt_duplicate', ['telegram_id', 'merchant_name', 'total_amount', 'date'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_constraint('uq_receipt_duplicate', type_='unique')

    # ### end Alembic commands ###